services:
  jenkins:
    image: jenkins:2.60.2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure    
    ports:
      - "8080:8080"
    privileged: true
    user: root
    
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins
    restart: unless-stopped

volumes:
  jenkins_home:
networks:
  jenkins:

