services:
  jenkins:
    image: jenkins/jenkins
    deploy:
      replicas: 10
      restart_policy:
        condition: on-failure    
    ports:
      - "8080:8080"
    privileged: true
       user: root
    
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped

volumes:
  jenkins_home:

